### ISSUE TITLE
"english" plugin title unhelpful

### ISSUE THREAD

**Issue by Stoatwblr** [InfotelGLPI/financialreports#6]
Please change from "asset situation" to "financial reports"

**Comment by keha35** [comment]
Hi,

Can you use transifex for translate the plugins : https://www.transifex.com/tsmr/GLPI_financialreports/.

Thx.

**Comment by Stoatwblr** [comment]
Unfortunately the "base language" of the plugin is supposedly english, not french.

I've put in a request for an english translation, but I think this might break things.

**Comment by keha35** [comment]
This will not break anything because you can't modifi the en_GB in transifex.
Sorry for the wrong information.

I will update this in the plugin and commit the changes.
